name: Bump Tags on Main

on:
  push:
    branches:
      - main

jobs:
  bump-tags:
    runs-on: blacksmith
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update v1 and v2 tags
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git tag -fa v1 -m "Update v1 tag to latest commit on main"
          git tag -fa v2 -m "Update v2 tag to latest commit on main"
          git push origin v1 v2 --force
      - name: Send Slack notification on success
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "Updated setup-node v1 and v2 tags to the latest commit on main"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CACHE_SLACK_WEBHOOK_URL }}